/**
 * Country / State / City fetch...
 */
export const LOAD_COUNTRIES = "LOAD_COUNTRIES";
export const LOAD_COUNTRIES_SUCCESS = "LOAD_COUNTRIES_SUCCESS";
export const LOAD_COUNTRIES_ERROR = "LOAD_COUNTRIES_ERROR";
export const LOAD_STATES = "LOAD_STATES";
export const LOAD_STATES_SUCCESS = "LOAD_STATES_SUCCESS";
export const LOAD_STATES_ERROR = "LOAD_STATES_ERROR";
export const LOAD_CITIES = "LOAD_CITIES";
export const LOAD_CITIES_SUCCESS = "LOAD_CITIES_SUCCESS";
export const LOAD_CITIES_ERROR = "LOAD_CITIES_ERROR";

/**
 * Country / State / City Dropdown item selection...
 */
export const COUNTRY_ITEM_SELECTION = 'COUNTRY_ITEM_SELECTION';
export const STATE_ITEM_SELECTION = 'STATE_ITEM_SELECTION';
export const CITY_ITEM_SELECTION = 'CITY_ITEM_SELECTION';

/**
 * Property fetch and CRUD...
 */
export const LOAD_PROPERTIES = 'LOAD_PROPERTIES';
export const LOAD_PROPERTIES_SUCCESS = 'LOAD_PROPERTIES_SUCCESS';
export const LOAD_PROPERTIES_ERROR = 'LOAD_PROPERTIES_ERROR';
export const SAVE_PROPERTY = 'SAVE_PROPERTY';
export const SAVE_PROPERTY_SUCCESS = 'SAVE_PROPERTY_SUCCESS';
export const SAVE_PROPERTY_ERROR = 'SAVE_PROPERTY_ERROR';
export const UPDATE_PROPERTY = 'UPDATE_PROPERTY';
export const UPDATE_PROPERTY_SUCCESS = 'UPDATE_PROPERTY_SUCCESS';
export const UPDATE_PROPERTY_ERROR = 'UPDATE_PROPERTY_ERROR';

/**
 * Add Property Modal actions...
 */
export const SET_ADDPROPERTY_DIALOG_DIALOG_VISIBILITY = 'SET_ADDPROPERTY_DIALOG_DIALOG_VISIBILITY';